'use client';

import Link from 'next/link';
import { Zap } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-white/50 hover:text-white/80 mb-8">
          <Zap className="h-5 w-5" />
          <span>Valnaa</span>
        </Link>

        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-white/50 text-sm mb-10">Last updated: {new Date().toLocaleDateString('en-US')}</p>

        <div className="space-y-6 text-[15px] leading-relaxed text-white/80">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Information We Collect</h2>
            <p>We collect account information (email, name), usage data, and data you provide when using our AI agent platform. Your agent conversations and workspace data are processed to deliver the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. How We Use Your Data</h2>
            <p>We use your data to operate the platform, improve our services, and communicate with you. We do not sell your personal data to third parties.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. Data Security</h2>
            <p>We implement reasonable security measures. However, we make no guarantee that your data will be secure. Data breaches, unauthorized access, loss, or corruption may occur. You use our services at your own risk.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. Third-Party Services</h2>
            <p>Our platform integrates with third-party AI providers (e.g., OpenRouter), cloud infrastructure, and payment processors. We are not responsible for their handling of your data. Their privacy policies apply. We have no control over and assume no liability for third-party practices.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. Your Rights</h2>
            <p>You may request access, correction, or deletion of your data. Contact us for such requests. We are not obligated to fulfill requests within any particular timeframe.</p>
          </section>

          <section className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4">
            <h2 className="text-lg font-semibold text-amber-400 mb-2">6. No Liability — Use at Your Own Risk</h2>
            <p className="text-amber-200/90 mb-3">
              <strong>To the maximum extent permitted by applicable law, we disclaim all liability</strong> for any loss, damage, harm, or claim arising from or related to your use of this platform, including but not limited to: data loss, data breach, unauthorized access, corruption, disclosure to third parties, actions taken by AI agents, outputs generated by AI, reliance on AI responses, third-party integrations, service interruptions, or any other cause. <strong>You use this service entirely at your own risk.</strong> You assume all risks. The service is provided &quot;as is&quot; without warranties of any kind, express or implied.
            </p>
            <p className="text-amber-200/90">
              In no event shall we be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, even if advised of the possibility of such damages.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10 flex gap-6 text-sm">
          <Link href="/terms" className="text-white/50 hover:text-white/80">Terms of Service</Link>
          <Link href="/help" className="text-white/50 hover:text-white/80">Help</Link>
          <Link href="/" className="text-white/50 hover:text-white/80">Home</Link>
        </div>
      </div>
    </div>
  );
}
